name: Build

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Build solution
        run: msbuild ./PhysicsGame.sln /p:Configuration=Release

      - name: Create artifact directory
        run: mkdir artifact

      - name: Copy the executable to the artifact directory
        run: copy ./Build/PhysicsGame/Release/Win32/PhysicsGame.exe artifact/

      - name: Copy Assets folder to the artifact directory
        run: robocopy ./Assets/ ./artifact/Assets/ /e; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: artifact/
          
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: my-app
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
            
